### ISSUE TITLE
Package disappeared from NuGet

### ISSUE THREAD

**Issue by sebafelis** [callumbwhyte/msbuild-umbraco-packaging#1]
I wont to use this in my project, but there is no MSBuild.Umbraco.Packaging package MSBuild.Umbraco.Packaging on NuGet.

**Comment by sebafelis** [comment]
I need this package so I was published it on NuGet myself.

**Comment by callumbwhyte** [comment]
Hello @sebafelis,

Apologies, I missed this issue before...

Thanks for your enthusiasm about my project!

However, the description clearly states this is a Work In Progress and I don't see it fit for release. There are better and supported solutions now (e.g. [UmbPack](https://our.umbraco.com/documentation/extending/Packages/UmbPack/)) to achieve similar results.

Unfortunately as you are now the owner of the NuGet package I have no way to release any updates to this in future... Perhaps you'd be so kind to transfer ownership to me?

Thanks,
Callum
